import React from 'react';

export const metadata = {
	title: 'About page',
	description: 'Generated by create next app',
};

const Page = () => {
	return (
		<>
			<div>This is my about page</div>
		</>
	);
};

export default Page;
