require('dotenv').config();
const nodemailer = require('nodemailer');

// async..await is not allowed in global scope, must use a wrapper
async function main() {
	// create reusable transporter object using the default SMTP transporttransport
	let transporter = nodemailer.createTransport({
		service: 'gmail',
		auth: {
			user: 'deependujha21@gmail.com', // sender's email address
			pass: process.env.NODE_MAILER_PASSWORD, // password generated by google for a custom app ->  https://security.google.com/settings/security/apppasswords
		},
	});

	// send mail with defined transport object
	let info = await transporter.sendMail({
		from: '"Drift-DAO 👻" drift-dao@gmail.com', // sender address
		to: 'deependujha16@gmail.com, nkumar35101@gmail.com', // list of receivers
		subject: 'Hello from Nodemailer', // Subject line
		text: 'Drift-DAO is going to rock...', // plain text body
		html: '<b>Woohoo..</b><p>Rebuilding of DRIFT-DAO has been started, and is expected to be released on 21 Dec, 2022.</p><p>Drift-DAO will reach the moon and beyond.</p><br><b>Thanks Deependu & Nitesh 🚀🔥<b/>', // html body
	});

	console.log('Message sent: %s', info.messageId);
	console.log('Email sent successfully');
}

main().catch(console.error);
